Initial work to add azuread_device table
turbot/steampipe-plugin-azuread pull request #68
Opened 2022-08-30 08:58 UTC by chrichts

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2022-08-31 06:29 UTC, chrichts commented
@cbruno10 - looks like the linter is failing because its running out of memory. I ran it locally and had no issues.

2022-08-31 11:17 UTC, cbruno10 commented
Hey @chrichts , yes unfortunately it's a known issue based on the size of the MS Graph Go SDK, please see https://github.com/microsoftgraph/msgraph-sdk-go/issues/129 for more information.

If it's passing locally, can you please paste your terminal output in this PR? Thanks!

2022-08-31 16:42 UTC, chrichts commented
Cool, looks like it passed this time around. I'll create a separate PR for the other issues I mentioned in Slack,

2022-09-02 07:05 UTC, Subhajit97 requested changes
@chrichts Thanks for submitting this PR! The table code looks great, I've added a few minor suggestions.

2022-09-02 07:05 UTC, Subhajit97 commented on azuread/table_azuread_device.go
> +			},
Apart from `display_name`, the other optional quals could also include the following parameters:
- accountEnabled
- deviceId
- operatingSystem
- operatingSystemVersion
- profileType
- trustType
- filter

Please refer https://github.com/turbot/steampipe-plugin-azuread/blob/main/azuread/table_azuread_user.go#L34-L44, for more information.

2022-09-02 07:05 UTC, Subhajit97 commented on azuread/table_azuread_device.go
> +
Can we add the following columns since they seem important?
- device_version
- device_metadata
- physical_ids

2022-09-02 07:05 UTC, Subhajit97 commented on azuread/table_azuread_device.go
> +		d.StreamLeafListItem(ctx, &ADDeviceInfo{device})
```suggestion
		d.StreamListItem(ctx, &ADDeviceInfo{device})
```
`StreamLeafListItem` is currently deprecated. Plugins should no longer call `StreamLeafListItem` directly and should call the `StreamListItem` event for the child list of a parent-child list call.

2022-09-05 04:46 UTC, chrichts commented on azuread/table_azuread_device.go
> +
These are marked in the API as "For internal use only". Not 100% sure what that means, but my experience is that properties marked as such don't contain any meaningful data.

https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0#properties

2022-09-05 04:50 UTC, chrichts commented on azuread/table_azuread_device.go
> +
Let me know if you still want me to add this anyway

2022-09-06 16:20 UTC, Subhajit97 commented
Hi @chrichts, thanks for the quick updates!
One more suggestion related to [MSGraph Go SDK](https://github.com/microsoftgraph/msgraph-sdk-go) version update.

As per https://github.com/microsoftgraph/msgraph-sdk-go/issues/129#issuecomment-1235546314, there are some build improvements in `v0.37.0`, and we have updated our plugin recently to use  [MSGraph Go SDK](https://github.com/microsoftgraph/msgraph-sdk-go) `v0.37.0`.

Can you please update your branch and made the required changes as per the latest SDK? Thanks!

2022-09-08 10:15 UTC, chrichts commented
@Subhajit97 - updated the go sdk version. Let me know if there is anything else

2022-09-09 15:01 UTC, Subhajit97 approved these changes

2022-09-09 15:03 UTC, merged

2022-09-09 15:05 UTC, Subhajit97 commented
Thanks again, @chrichts, for this addition! We'll release this in our next plugin release.